### ISSUE TITLE
OkHttp provider Bug

### ISSUE THREAD

**Issue by i0x404** [ImZaw/cloudstream-extensions-arabic#16]
Hello, 
It seems that there is a bug with the arabic providers when using the search button and filter some providers from the list the app crashes. 
The problem is fixed when I disable alll arabic providers.
![Screenshot_20220911-033001_CloudStream Beta](https://user-images.githubusercontent.com/74503778/189510065-f47f5e7f-e09e-47e9-8ea5-191203192c98.png)

![Screenshot_20220911-033031_CloudStream Beta](https://user-images.githubusercontent.com/74503778/189510092-4419ec4c-c224-433b-b214-d1b192fc66fb.png)

**Comment by ImZaw** [comment]
maybe that is an app issue, or ur side issue try vpn/dns. i only accept issues **with** providers (`Providers works perfectly fine, most of them with a lot of users`)
