### ISSUE TITLE
ممكن حل لموقع ايجي بست يدخل على القوائم و لكن عند تشغيل فيدو لا يشتغل

### ISSUE THREAD

**Issue by Djadjou007** [ImZaw/cloudstream-extensions-arabic#24]
ممكن حل لموقع ايجي بست يدخل على القوائم و لكن عند تشغيل فيدو لا يشتغل

_Originally posted by @Djadjou007 in https://github.com/ImZaw/cloudstream-extensions-arabic/issues/8#issuecomment-1262980193_

**Comment by ImZaw** [comment]
> ```
>     ممكن حل لموقع ايجي بست يدخل على القوائم و لكن عند تشغيل فيدو لا يشتغل
> ```
> 
> _Originally posted by @Djadjou007 in [#8 (comment)](https://github.com/ImZaw/cloudstream-extensions-arabic/issues/8#issuecomment-1262980193)_

Known issue, and it is disabled
